// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: worker/database/v1/document_service.proto

package dbv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_worker_database_v1_document_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_worker_database_v1_document_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_worker_database_v1_document_service_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_worker_database_v1_document_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_database_v1_document_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_worker_database_v1_document_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListDocumentsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_worker_database_v1_document_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_database_v1_document_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_worker_database_v1_document_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_worker_database_v1_document_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_database_v1_document_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_worker_database_v1_document_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Document      *Document              `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_worker_database_v1_document_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_database_v1_document_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_worker_database_v1_document_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDocumentRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateDocumentRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_worker_database_v1_document_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_database_v1_document_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_worker_database_v1_document_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDocumentRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *UpdateDocumentRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_worker_database_v1_document_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_database_v1_document_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_worker_database_v1_document_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_worker_database_v1_document_service_proto protoreflect.FileDescriptor

const file_worker_database_v1_document_service_proto_rawDesc = "" +
	"\n" +
	")worker/database/v1/document_service.proto\x12\x12worker.database.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x17validate/validate.proto\"\xe3\x02\n" +
	"\bDocument\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x123\n" +
	"\x02id\x18\x02 \x01(\tB#\xe0A\x04\xfaB\x1dr\x1b\x10\x01\x18@2\x12^[a-zA-Z0-9\\-_.]*$\xd0\x01\x01R\x02id\x12#\n" +
	"\x05value\x18\x03 \x01(\tB\r\xe0A\x02\xfaB\ar\x05\x10\x01\x18\x80 R\x05value\x12>\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt:d\xeaAa\n" +
	"\x1bworker.database.v1/Document\x12Bdatabases/{database}/collections/{collection}/documents/{document}\"\xaa\x01\n" +
	"\x14ListDocumentsRequest\x12J\n" +
	"\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaB,r*2(^databases\\/[^\\/]+\\/collections\\/[^\\/]+$R\x06parent\x12'\n" +
	"\tpage_size\x18\x02 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"{\n" +
	"\x15ListDocumentsResponse\x12:\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1c.worker.database.v1.DocumentR\tdocuments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"o\n" +
	"\x12GetDocumentRequest\x12Y\n" +
	"\x04name\x18\x01 \x01(\tBE\xe0A\x02\xfaB?r=2;^databases\\/[^\\/]+\\/collections\\/[^\\/]+\\/documents\\/[^\\/]+$R\x04name\"\xf0\x01\n" +
	"\x15CreateDocumentRequest\x12J\n" +
	"\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaB,r*2(^databases\\/[^\\/]+\\/collections\\/[^\\/]+$R\x06parent\x12D\n" +
	"\vdocument_id\x18\x02 \x01(\tB#\xe0A\x01\xfaB\x1dr\x1b\x10\x01\x18@2\x12^[a-zA-Z0-9\\-_.]*$\xd0\x01\x01R\n" +
	"documentId\x12E\n" +
	"\bdocument\x18\x03 \x01(\v2\x1c.worker.database.v1.DocumentB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\bdocument\"\x9b\x01\n" +
	"\x15UpdateDocumentRequest\x12E\n" +
	"\bdocument\x18\x01 \x01(\v2\x1c.worker.database.v1.DocumentB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\bdocument\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"r\n" +
	"\x15DeleteDocumentRequest\x12Y\n" +
	"\x04name\x18\x01 \x01(\tBE\xe0A\x02\xfaB?r=2;^databases\\/[^\\/]+\\/collections\\/[^\\/]+\\/documents\\/[^\\/]+$R\x04name2\xb9\x06\n" +
	"\x0fDocumentService\x12\xa4\x01\n" +
	"\rListDocuments\x12(.worker.database.v1.ListDocumentsRequest\x1a).worker.database.v1.ListDocumentsResponse\">\x82\xd3\xe4\x93\x028\x126/v1alpha1/{parent=databases/*/collections/*}/documents\x12\x93\x01\n" +
	"\vGetDocument\x12&.worker.database.v1.GetDocumentRequest\x1a\x1c.worker.database.v1.Document\">\x82\xd3\xe4\x93\x028\x126/v1alpha1/{name=databases/*/collections/*/documents/*}\x12\xa3\x01\n" +
	"\x0eCreateDocument\x12).worker.database.v1.CreateDocumentRequest\x1a\x1c.worker.database.v1.Document\"H\x82\xd3\xe4\x93\x02B:\bdocument\"6/v1alpha1/{parent=databases/*/collections/*}/documents\x12\xac\x01\n" +
	"\x0eUpdateDocument\x12).worker.database.v1.UpdateDocumentRequest\x1a\x1c.worker.database.v1.Document\"Q\x82\xd3\xe4\x93\x02K:\bdocument2?/v1alpha1/{document.name=databases/*/collections/*/documents/*}\x12\x93\x01\n" +
	"\x0eDeleteDocument\x12).worker.database.v1.DeleteDocumentRequest\x1a\x16.google.protobuf.Empty\">\x82\xd3\xe4\x93\x028*6/v1alpha1/{name=databases/*/collections/*/documents/*}Bf\n" +
	"\x1dcom.google.worker.database.v1P\x01ZCgithub.com/10Narratives/distgo-db/pkg/proto/worker/database/v1;dbv1b\x06proto3"

var (
	file_worker_database_v1_document_service_proto_rawDescOnce sync.Once
	file_worker_database_v1_document_service_proto_rawDescData []byte
)

func file_worker_database_v1_document_service_proto_rawDescGZIP() []byte {
	file_worker_database_v1_document_service_proto_rawDescOnce.Do(func() {
		file_worker_database_v1_document_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_database_v1_document_service_proto_rawDesc), len(file_worker_database_v1_document_service_proto_rawDesc)))
	})
	return file_worker_database_v1_document_service_proto_rawDescData
}

var file_worker_database_v1_document_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_worker_database_v1_document_service_proto_goTypes = []any{
	(*Document)(nil),              // 0: worker.database.v1.Document
	(*ListDocumentsRequest)(nil),  // 1: worker.database.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil), // 2: worker.database.v1.ListDocumentsResponse
	(*GetDocumentRequest)(nil),    // 3: worker.database.v1.GetDocumentRequest
	(*CreateDocumentRequest)(nil), // 4: worker.database.v1.CreateDocumentRequest
	(*UpdateDocumentRequest)(nil), // 5: worker.database.v1.UpdateDocumentRequest
	(*DeleteDocumentRequest)(nil), // 6: worker.database.v1.DeleteDocumentRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 8: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_worker_database_v1_document_service_proto_depIdxs = []int32{
	7,  // 0: worker.database.v1.Document.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: worker.database.v1.Document.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: worker.database.v1.ListDocumentsResponse.documents:type_name -> worker.database.v1.Document
	0,  // 3: worker.database.v1.CreateDocumentRequest.document:type_name -> worker.database.v1.Document
	0,  // 4: worker.database.v1.UpdateDocumentRequest.document:type_name -> worker.database.v1.Document
	8,  // 5: worker.database.v1.UpdateDocumentRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 6: worker.database.v1.DocumentService.ListDocuments:input_type -> worker.database.v1.ListDocumentsRequest
	3,  // 7: worker.database.v1.DocumentService.GetDocument:input_type -> worker.database.v1.GetDocumentRequest
	4,  // 8: worker.database.v1.DocumentService.CreateDocument:input_type -> worker.database.v1.CreateDocumentRequest
	5,  // 9: worker.database.v1.DocumentService.UpdateDocument:input_type -> worker.database.v1.UpdateDocumentRequest
	6,  // 10: worker.database.v1.DocumentService.DeleteDocument:input_type -> worker.database.v1.DeleteDocumentRequest
	2,  // 11: worker.database.v1.DocumentService.ListDocuments:output_type -> worker.database.v1.ListDocumentsResponse
	0,  // 12: worker.database.v1.DocumentService.GetDocument:output_type -> worker.database.v1.Document
	0,  // 13: worker.database.v1.DocumentService.CreateDocument:output_type -> worker.database.v1.Document
	0,  // 14: worker.database.v1.DocumentService.UpdateDocument:output_type -> worker.database.v1.Document
	9,  // 15: worker.database.v1.DocumentService.DeleteDocument:output_type -> google.protobuf.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_worker_database_v1_document_service_proto_init() }
func file_worker_database_v1_document_service_proto_init() {
	if File_worker_database_v1_document_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_database_v1_document_service_proto_rawDesc), len(file_worker_database_v1_document_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_database_v1_document_service_proto_goTypes,
		DependencyIndexes: file_worker_database_v1_document_service_proto_depIdxs,
		MessageInfos:      file_worker_database_v1_document_service_proto_msgTypes,
	}.Build()
	File_worker_database_v1_document_service_proto = out.File
	file_worker_database_v1_document_service_proto_goTypes = nil
	file_worker_database_v1_document_service_proto_depIdxs = nil
}
