// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: worker/database/v1/entity_type.proto

package dbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED EntityType = 0
	EntityType_ENTITY_TYPE_DATABASE    EntityType = 1
	EntityType_ENTITY_TYPE_COLLECTION  EntityType = 2
	EntityType_ENTITY_TYPE_DOCUMENT    EntityType = 3
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "ENTITY_TYPE_DATABASE",
		2: "ENTITY_TYPE_COLLECTION",
		3: "ENTITY_TYPE_DOCUMENT",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED": 0,
		"ENTITY_TYPE_DATABASE":    1,
		"ENTITY_TYPE_COLLECTION":  2,
		"ENTITY_TYPE_DOCUMENT":    3,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_database_v1_entity_type_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_worker_database_v1_entity_type_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_worker_database_v1_entity_type_proto_rawDescGZIP(), []int{0}
}

var File_worker_database_v1_entity_type_proto protoreflect.FileDescriptor

const file_worker_database_v1_entity_type_proto_rawDesc = "" +
	"\n" +
	"$worker/database/v1/entity_type.proto\x12\x12worker.database.v1*y\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ENTITY_TYPE_DATABASE\x10\x01\x12\x1a\n" +
	"\x16ENTITY_TYPE_COLLECTION\x10\x02\x12\x18\n" +
	"\x14ENTITY_TYPE_DOCUMENT\x10\x03Bf\n" +
	"\x1dcom.google.worker.database.v1P\x01ZCgithub.com/10Narratives/distgo-db/pkg/proto/worker/database/v1;dbv1b\x06proto3"

var (
	file_worker_database_v1_entity_type_proto_rawDescOnce sync.Once
	file_worker_database_v1_entity_type_proto_rawDescData []byte
)

func file_worker_database_v1_entity_type_proto_rawDescGZIP() []byte {
	file_worker_database_v1_entity_type_proto_rawDescOnce.Do(func() {
		file_worker_database_v1_entity_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_database_v1_entity_type_proto_rawDesc), len(file_worker_database_v1_entity_type_proto_rawDesc)))
	})
	return file_worker_database_v1_entity_type_proto_rawDescData
}

var file_worker_database_v1_entity_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_database_v1_entity_type_proto_goTypes = []any{
	(EntityType)(0), // 0: worker.database.v1.EntityType
}
var file_worker_database_v1_entity_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_worker_database_v1_entity_type_proto_init() }
func file_worker_database_v1_entity_type_proto_init() {
	if File_worker_database_v1_entity_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_database_v1_entity_type_proto_rawDesc), len(file_worker_database_v1_entity_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_worker_database_v1_entity_type_proto_goTypes,
		DependencyIndexes: file_worker_database_v1_entity_type_proto_depIdxs,
		EnumInfos:         file_worker_database_v1_entity_type_proto_enumTypes,
	}.Build()
	File_worker_database_v1_entity_type_proto = out.File
	file_worker_database_v1_entity_type_proto_goTypes = nil
	file_worker_database_v1_entity_type_proto_depIdxs = nil
}
