// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: worker/database/v1/mutation_type.proto

package dbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutationType int32

const (
	MutationType_MUTATION_TYPE_UNSPECIFIED MutationType = 0
	MutationType_MUTATION_TYPE_CREATE      MutationType = 1
	MutationType_MUTATION_TYPE_UPDATE      MutationType = 2
	MutationType_MUTATION_TYPE_DELETE      MutationType = 3
)

// Enum value maps for MutationType.
var (
	MutationType_name = map[int32]string{
		0: "MUTATION_TYPE_UNSPECIFIED",
		1: "MUTATION_TYPE_CREATE",
		2: "MUTATION_TYPE_UPDATE",
		3: "MUTATION_TYPE_DELETE",
	}
	MutationType_value = map[string]int32{
		"MUTATION_TYPE_UNSPECIFIED": 0,
		"MUTATION_TYPE_CREATE":      1,
		"MUTATION_TYPE_UPDATE":      2,
		"MUTATION_TYPE_DELETE":      3,
	}
)

func (x MutationType) Enum() *MutationType {
	p := new(MutationType)
	*p = x
	return p
}

func (x MutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_database_v1_mutation_type_proto_enumTypes[0].Descriptor()
}

func (MutationType) Type() protoreflect.EnumType {
	return &file_worker_database_v1_mutation_type_proto_enumTypes[0]
}

func (x MutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationType.Descriptor instead.
func (MutationType) EnumDescriptor() ([]byte, []int) {
	return file_worker_database_v1_mutation_type_proto_rawDescGZIP(), []int{0}
}

var File_worker_database_v1_mutation_type_proto protoreflect.FileDescriptor

const file_worker_database_v1_mutation_type_proto_rawDesc = "" +
	"\n" +
	"&worker/database/v1/mutation_type.proto\x12\x12worker.database.v1*{\n" +
	"\fMutationType\x12\x1d\n" +
	"\x19MUTATION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MUTATION_TYPE_CREATE\x10\x01\x12\x18\n" +
	"\x14MUTATION_TYPE_UPDATE\x10\x02\x12\x18\n" +
	"\x14MUTATION_TYPE_DELETE\x10\x03Bf\n" +
	"\x1dcom.google.worker.database.v1P\x01ZCgithub.com/10Narratives/distgo-db/pkg/proto/worker/database/v1;dbv1b\x06proto3"

var (
	file_worker_database_v1_mutation_type_proto_rawDescOnce sync.Once
	file_worker_database_v1_mutation_type_proto_rawDescData []byte
)

func file_worker_database_v1_mutation_type_proto_rawDescGZIP() []byte {
	file_worker_database_v1_mutation_type_proto_rawDescOnce.Do(func() {
		file_worker_database_v1_mutation_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_database_v1_mutation_type_proto_rawDesc), len(file_worker_database_v1_mutation_type_proto_rawDesc)))
	})
	return file_worker_database_v1_mutation_type_proto_rawDescData
}

var file_worker_database_v1_mutation_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_database_v1_mutation_type_proto_goTypes = []any{
	(MutationType)(0), // 0: worker.database.v1.MutationType
}
var file_worker_database_v1_mutation_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_worker_database_v1_mutation_type_proto_init() }
func file_worker_database_v1_mutation_type_proto_init() {
	if File_worker_database_v1_mutation_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_database_v1_mutation_type_proto_rawDesc), len(file_worker_database_v1_mutation_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_worker_database_v1_mutation_type_proto_goTypes,
		DependencyIndexes: file_worker_database_v1_mutation_type_proto_depIdxs,
		EnumInfos:         file_worker_database_v1_mutation_type_proto_enumTypes,
	}.Build()
	File_worker_database_v1_mutation_type_proto = out.File
	file_worker_database_v1_mutation_type_proto_goTypes = nil
	file_worker_database_v1_mutation_type_proto_depIdxs = nil
}
