// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	commonmodels "github.com/10Narratives/distgo-db/internal/models/worker/data/common"

	documentmodels "github.com/10Narratives/distgo-db/internal/models/worker/data/document"

	mock "github.com/stretchr/testify/mock"
)

// WALService is an autogenerated mock type for the WALService type
type WALService struct {
	mock.Mock
}

// CreateDocumentEntry provides a mock function with given fields: ctx, mutation, key, doc
func (_m *WALService) CreateDocumentEntry(ctx context.Context, mutation commonmodels.MutationType, key documentmodels.Key, doc *documentmodels.Document) error {
	ret := _m.Called(ctx, mutation, key, doc)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocumentEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commonmodels.MutationType, documentmodels.Key, *documentmodels.Document) error); ok {
		r0 = rf(ctx, mutation, key, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWALService creates a new instance of WALService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWALService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WALService {
	mock := &WALService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
