// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	databasemodels "github.com/10Narratives/distgo-db/internal/models/worker/data/database"

	mock "github.com/stretchr/testify/mock"
)

// DatabaseStorage is an autogenerated mock type for the DatabaseStorage type
type DatabaseStorage struct {
	mock.Mock
}

// CreateDatabase provides a mock function with given fields: ctx, name, displayName
func (_m *DatabaseStorage) CreateDatabase(ctx context.Context, name string, displayName string) (databasemodels.Database, error) {
	ret := _m.Called(ctx, name, displayName)

	if len(ret) == 0 {
		panic("no return value specified for CreateDatabase")
	}

	var r0 databasemodels.Database
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (databasemodels.Database, error)); ok {
		return rf(ctx, name, displayName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) databasemodels.Database); ok {
		r0 = rf(ctx, name, displayName)
	} else {
		r0 = ret.Get(0).(databasemodels.Database)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, displayName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database provides a mock function with given fields: ctx, name
func (_m *DatabaseStorage) Database(ctx context.Context, name string) (databasemodels.Database, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 databasemodels.Database
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (databasemodels.Database, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) databasemodels.Database); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(databasemodels.Database)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Databases provides a mock function with given fields: ctx
func (_m *DatabaseStorage) Databases(ctx context.Context) []databasemodels.Database {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Databases")
	}

	var r0 []databasemodels.Database
	if rf, ok := ret.Get(0).(func(context.Context) []databasemodels.Database); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]databasemodels.Database)
		}
	}

	return r0
}

// DeleteDatabase provides a mock function with given fields: ctx, name
func (_m *DatabaseStorage) DeleteDatabase(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDatabase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDatabase provides a mock function with given fields: ctx, name, displayName
func (_m *DatabaseStorage) UpdateDatabase(ctx context.Context, name string, displayName string) error {
	ret := _m.Called(ctx, name, displayName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDatabase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, displayName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDatabaseStorage creates a new instance of DatabaseStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseStorage {
	mock := &DatabaseStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
