// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	documentmodels "github.com/10Narratives/distgo-db/internal/models/worker/data/document"

	mock "github.com/stretchr/testify/mock"
)

// DocumentService is an autogenerated mock type for the DocumentService type
type DocumentService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, collection, documentID, value
func (_m *DocumentService) Create(ctx context.Context, collection string, documentID string, value string) (documentmodels.Document, error) {
	ret := _m.Called(ctx, collection, documentID, value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 documentmodels.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (documentmodels.Document, error)); ok {
		return rf(ctx, collection, documentID, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) documentmodels.Document); ok {
		r0 = rf(ctx, collection, documentID, value)
	} else {
		r0 = ret.Get(0).(documentmodels.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, collection, documentID, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, collection, documentID
func (_m *DocumentService) Delete(ctx context.Context, collection string, documentID string) error {
	ret := _m.Called(ctx, collection, documentID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, collection, documentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Document provides a mock function with given fields: ctx, collection, documentID
func (_m *DocumentService) Document(ctx context.Context, collection string, documentID string) (documentmodels.Document, error) {
	ret := _m.Called(ctx, collection, documentID)

	if len(ret) == 0 {
		panic("no return value specified for Document")
	}

	var r0 documentmodels.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (documentmodels.Document, error)); ok {
		return rf(ctx, collection, documentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) documentmodels.Document); ok {
		r0 = rf(ctx, collection, documentID)
	} else {
		r0 = ret.Get(0).(documentmodels.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, collection, documentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Documents provides a mock function with given fields: ctx, collection, pageSize, pageToken
func (_m *DocumentService) Documents(ctx context.Context, collection string, pageSize int32, pageToken string) ([]documentmodels.Document, error) {
	ret := _m.Called(ctx, collection, pageSize, pageToken)

	if len(ret) == 0 {
		panic("no return value specified for Documents")
	}

	var r0 []documentmodels.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, string) ([]documentmodels.Document, error)); ok {
		return rf(ctx, collection, pageSize, pageToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, string) []documentmodels.Document); ok {
		r0 = rf(ctx, collection, pageSize, pageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]documentmodels.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, string) error); ok {
		r1 = rf(ctx, collection, pageSize, pageToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, collection, documentID, value, paths
func (_m *DocumentService) Update(ctx context.Context, collection string, documentID string, value string, paths []string) (documentmodels.Document, error) {
	ret := _m.Called(ctx, collection, documentID, value, paths)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 documentmodels.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) (documentmodels.Document, error)); ok {
		return rf(ctx, collection, documentID, value, paths)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) documentmodels.Document); ok {
		r0 = rf(ctx, collection, documentID, value, paths)
	} else {
		r0 = ret.Get(0).(documentmodels.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []string) error); ok {
		r1 = rf(ctx, collection, documentID, value, paths)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDocumentService creates a new instance of DocumentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocumentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentService {
	mock := &DocumentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
