// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: master/database/v1/transaction_service.proto

package mdbv1

import (
	v1 "github.com/10Narratives/distgo-db/pkg/proto/worker/database/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MutationType  v1.MutationType        `protobuf:"varint,1,opt,name=mutation_type,json=mutationType,proto3,enum=worker.database.v1.MutationType" json:"mutation_type,omitempty"`
	EntityType    v1.EntityType          `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=worker.database.v1.EntityType" json:"entity_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_master_database_v1_transaction_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_master_database_v1_transaction_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_master_database_v1_transaction_service_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetMutationType() v1.MutationType {
	if x != nil {
		return x.MutationType
	}
	return v1.MutationType(0)
}

func (x *Operation) GetEntityType() v1.EntityType {
	if x != nil {
		return x.EntityType
	}
	return v1.EntityType(0)
}

func (x *Operation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Operations    []*Operation           `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_master_database_v1_transaction_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_database_v1_transaction_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_master_database_v1_transaction_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *ExecuteRequest) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

var File_master_database_v1_transaction_service_proto protoreflect.FileDescriptor

const file_master_database_v1_transaction_service_proto_rawDesc = "" +
	"\n" +
	",master/database/v1/transaction_service.proto\x12\x12master.database.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a&worker/database/v1/mutation_type.proto\x1a$worker/database/v1/entity_type.proto\x1a\x17validate/validate.proto\"\xda\x01\n" +
	"\tOperation\x12O\n" +
	"\rmutation_type\x18\x01 \x01(\x0e2 .worker.database.v1.MutationTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\fmutationType\x12I\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x1e.worker.database.v1.EntityTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\n" +
	"entityType\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x8e\x01\n" +
	"\x0eExecuteRequest\x12,\n" +
	"\rdatabase_name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\fdatabaseName\x12N\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x1d.master.database.v1.OperationB\x0f\xfaB\f\x92\x01\t\b\x01\"\x05\x8a\x01\x02\x10\x01R\n" +
	"operations2[\n" +
	"\x12TransactionService\x12E\n" +
	"\aExecute\x12\".master.database.v1.ExecuteRequest\x1a\x16.google.protobuf.EmptyBg\n" +
	"\x1dcom.google.master.database.v1P\x01ZDgithub.com/10Narratives/distgo-db/pkg/proto/master/database/v1;mdbv1b\x06proto3"

var (
	file_master_database_v1_transaction_service_proto_rawDescOnce sync.Once
	file_master_database_v1_transaction_service_proto_rawDescData []byte
)

func file_master_database_v1_transaction_service_proto_rawDescGZIP() []byte {
	file_master_database_v1_transaction_service_proto_rawDescOnce.Do(func() {
		file_master_database_v1_transaction_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_database_v1_transaction_service_proto_rawDesc), len(file_master_database_v1_transaction_service_proto_rawDesc)))
	})
	return file_master_database_v1_transaction_service_proto_rawDescData
}

var file_master_database_v1_transaction_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_master_database_v1_transaction_service_proto_goTypes = []any{
	(*Operation)(nil),      // 0: master.database.v1.Operation
	(*ExecuteRequest)(nil), // 1: master.database.v1.ExecuteRequest
	(v1.MutationType)(0),   // 2: worker.database.v1.MutationType
	(v1.EntityType)(0),     // 3: worker.database.v1.EntityType
	(*emptypb.Empty)(nil),  // 4: google.protobuf.Empty
}
var file_master_database_v1_transaction_service_proto_depIdxs = []int32{
	2, // 0: master.database.v1.Operation.mutation_type:type_name -> worker.database.v1.MutationType
	3, // 1: master.database.v1.Operation.entity_type:type_name -> worker.database.v1.EntityType
	0, // 2: master.database.v1.ExecuteRequest.operations:type_name -> master.database.v1.Operation
	1, // 3: master.database.v1.TransactionService.Execute:input_type -> master.database.v1.ExecuteRequest
	4, // 4: master.database.v1.TransactionService.Execute:output_type -> google.protobuf.Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_master_database_v1_transaction_service_proto_init() }
func file_master_database_v1_transaction_service_proto_init() {
	if File_master_database_v1_transaction_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_database_v1_transaction_service_proto_rawDesc), len(file_master_database_v1_transaction_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_database_v1_transaction_service_proto_goTypes,
		DependencyIndexes: file_master_database_v1_transaction_service_proto_depIdxs,
		MessageInfos:      file_master_database_v1_transaction_service_proto_msgTypes,
	}.Build()
	File_master_database_v1_transaction_service_proto = out.File
	file_master_database_v1_transaction_service_proto_goTypes = nil
	file_master_database_v1_transaction_service_proto_depIdxs = nil
}
