// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/worker/worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_OK                  StatusCode = 0
	StatusCode_NOT_FOUND           StatusCode = 1
	StatusCode_CONFLICT            StatusCode = 2
	StatusCode_INVALID_ARGUMENT    StatusCode = 3
	StatusCode_INTERNAL_ERROR      StatusCode = 4
	StatusCode_PERMISSION_DENIED   StatusCode = 5
	StatusCode_UNAUTHENTICATED     StatusCode = 6
	StatusCode_RESOURCE_EXHAUSTED  StatusCode = 7
	StatusCode_FAILED_PRECONDITION StatusCode = 8
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "CONFLICT",
		3: "INVALID_ARGUMENT",
		4: "INTERNAL_ERROR",
		5: "PERMISSION_DENIED",
		6: "UNAUTHENTICATED",
		7: "RESOURCE_EXHAUSTED",
		8: "FAILED_PRECONDITION",
	}
	StatusCode_value = map[string]int32{
		"OK":                  0,
		"NOT_FOUND":           1,
		"CONFLICT":            2,
		"INVALID_ARGUMENT":    3,
		"INTERNAL_ERROR":      4,
		"PERMISSION_DENIED":   5,
		"UNAUTHENTICATED":     6,
		"RESOURCE_EXHAUSTED":  7,
		"FAILED_PRECONDITION": 8,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_worker_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_proto_worker_worker_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{0}
}

type ReplicaRole int32

const (
	ReplicaRole_FOLLOWER  ReplicaRole = 0
	ReplicaRole_CANDIDATE ReplicaRole = 1
	ReplicaRole_LEADER    ReplicaRole = 2
	ReplicaRole_LEARNER   ReplicaRole = 3
)

// Enum value maps for ReplicaRole.
var (
	ReplicaRole_name = map[int32]string{
		0: "FOLLOWER",
		1: "CANDIDATE",
		2: "LEADER",
		3: "LEARNER",
	}
	ReplicaRole_value = map[string]int32{
		"FOLLOWER":  0,
		"CANDIDATE": 1,
		"LEADER":    2,
		"LEARNER":   3,
	}
)

func (x ReplicaRole) Enum() *ReplicaRole {
	p := new(ReplicaRole)
	*p = x
	return p
}

func (x ReplicaRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicaRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_worker_proto_enumTypes[1].Descriptor()
}

func (ReplicaRole) Type() protoreflect.EnumType {
	return &file_proto_worker_worker_proto_enumTypes[1]
}

func (x ReplicaRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicaRole.Descriptor instead.
func (ReplicaRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{1}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=worker.StatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_OK
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Document) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ReplicaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Role          ReplicaRole            `protobuf:"varint,3,opt,name=role,proto3,enum=worker.ReplicaRole" json:"role,omitempty"`
	Term          uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,5,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,6,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Syncing       bool                   `protobuf:"varint,7,opt,name=syncing,proto3" json:"syncing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaInfo) Reset() {
	*x = ReplicaInfo{}
	mi := &file_proto_worker_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaInfo) ProtoMessage() {}

func (x *ReplicaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaInfo.ProtoReflect.Descriptor instead.
func (*ReplicaInfo) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicaInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReplicaInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReplicaInfo) GetRole() ReplicaRole {
	if x != nil {
		return x.Role
	}
	return ReplicaRole_FOLLOWER
}

func (x *ReplicaInfo) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ReplicaInfo) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *ReplicaInfo) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *ReplicaInfo) GetSyncing() bool {
	if x != nil {
		return x.Syncing
	}
	return false
}

type NodeStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsage          float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsedMb      uint64                 `protobuf:"varint,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryTotalMb     uint64                 `protobuf:"varint,4,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	ActiveConnections uint32                 `protobuf:"varint,5,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeStats) Reset() {
	*x = NodeStats{}
	mi := &file_proto_worker_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStats) ProtoMessage() {}

func (x *NodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStats.ProtoReflect.Descriptor instead.
func (*NodeStats) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStats) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeStats) GetMemoryUsedMb() uint64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *NodeStats) GetMemoryTotalMb() uint64 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *NodeStats) GetActiveConnections() uint32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

type ClusterHealth struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalNodes            uint32                 `protobuf:"varint,1,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	HealthyNodes          uint32                 `protobuf:"varint,2,opt,name=healthy_nodes,json=healthyNodes,proto3" json:"healthy_nodes,omitempty"`
	UnderReplicatedShards uint32                 `protobuf:"varint,3,opt,name=under_replicated_shards,json=underReplicatedShards,proto3" json:"under_replicated_shards,omitempty"`
	NodeStats             []*NodeStats           `protobuf:"bytes,4,rep,name=node_stats,json=nodeStats,proto3" json:"node_stats,omitempty"`
	ReportTime            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=report_time,json=reportTime,proto3" json:"report_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClusterHealth) Reset() {
	*x = ClusterHealth{}
	mi := &file_proto_worker_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterHealth) ProtoMessage() {}

func (x *ClusterHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterHealth.ProtoReflect.Descriptor instead.
func (*ClusterHealth) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterHealth) GetTotalNodes() uint32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *ClusterHealth) GetHealthyNodes() uint32 {
	if x != nil {
		return x.HealthyNodes
	}
	return 0
}

func (x *ClusterHealth) GetUnderReplicatedShards() uint32 {
	if x != nil {
		return x.UnderReplicatedShards
	}
	return 0
}

func (x *ClusterHealth) GetNodeStats() []*NodeStats {
	if x != nil {
		return x.NodeStats
	}
	return nil
}

func (x *ClusterHealth) GetReportTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportTime
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_worker_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{5}
}

type CreateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Document      *structpb.Struct       `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CreateDocumentRequest) GetDocument() *structpb.Struct {
	if x != nil {
		return x.Document
	}
	return nil
}

type CreateDocumentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CreatedDocument *Document              `protobuf:"bytes,1,opt,name=created_document,json=createdDocument,proto3" json:"created_document,omitempty"`
	Status          *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDocumentResponse) Reset() {
	*x = CreateDocumentResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentResponse) ProtoMessage() {}

func (x *CreateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDocumentResponse) GetCreatedDocument() *Document {
	if x != nil {
		return x.CreatedDocument
	}
	return nil
}

func (x *CreateDocumentResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Collection      string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	IncludeMetadata bool                   `protobuf:"varint,3,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{8}
}

func (x *GetDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{9}
}

func (x *GetDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetDocumentResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{10}
}

func (x *ListDocumentsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Status        *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{11}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Update        *structpb.Struct       `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	IfRevision    *int64                 `protobuf:"varint,4,opt,name=if_revision,json=ifRevision,proto3,oneof" json:"if_revision,omitempty"`
	Upsert        bool                   `protobuf:"varint,5,opt,name=upsert,proto3" json:"upsert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetUpdate() *structpb.Struct {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateDocumentRequest) GetIfRevision() int64 {
	if x != nil && x.IfRevision != nil {
		return *x.IfRevision
	}
	return 0
}

func (x *UpdateDocumentRequest) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

type UpdateDocumentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpdatedDocument *Document              `protobuf:"bytes,1,opt,name=updated_document,json=updatedDocument,proto3" json:"updated_document,omitempty"`
	Status          *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateDocumentResponse) Reset() {
	*x = UpdateDocumentResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentResponse) ProtoMessage() {}

func (x *UpdateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDocumentResponse) GetUpdatedDocument() *Document {
	if x != nil {
		return x.UpdatedDocument
	}
	return nil
}

func (x *UpdateDocumentResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	IfRevision    *int64                 `protobuf:"varint,3,opt,name=if_revision,json=ifRevision,proto3,oneof" json:"if_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DeleteDocumentRequest) GetIfRevision() int64 {
	if x != nil && x.IfRevision != nil {
		return *x.IfRevision
	}
	return 0
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDocumentResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_proto_worker_worker_proto protoreflect.FileDescriptor

const file_proto_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x19proto/worker/worker.proto\x12\x06worker\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\x06Status\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.worker.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\"\xd9\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x01\n" +
	"\vReplicaInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12'\n" +
	"\x04role\x18\x03 \x01(\x0e2\x13.worker.ReplicaRoleR\x04role\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12$\n" +
	"\x0elast_log_index\x18\x05 \x01(\x04R\flastLogIndex\x12!\n" +
	"\fcommit_index\x18\x06 \x01(\x04R\vcommitIndex\x12\x18\n" +
	"\asyncing\x18\a \x01(\bR\asyncing\"\xbe\x01\n" +
	"\tNodeStats\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x04R\fmemoryUsedMb\x12&\n" +
	"\x0fmemory_total_mb\x18\x04 \x01(\x04R\rmemoryTotalMb\x12-\n" +
	"\x12active_connections\x18\x05 \x01(\rR\x11activeConnections\"\xfc\x01\n" +
	"\rClusterHealth\x12\x1f\n" +
	"\vtotal_nodes\x18\x01 \x01(\rR\n" +
	"totalNodes\x12#\n" +
	"\rhealthy_nodes\x18\x02 \x01(\rR\fhealthyNodes\x126\n" +
	"\x17under_replicated_shards\x18\x03 \x01(\rR\x15underReplicatedShards\x120\n" +
	"\n" +
	"node_stats\x18\x04 \x03(\v2\x11.worker.NodeStatsR\tnodeStats\x12;\n" +
	"\vreport_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportTime\"\a\n" +
	"\x05Empty\"l\n" +
	"\x15CreateDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x123\n" +
	"\bdocument\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bdocument\"}\n" +
	"\x16CreateDocumentResponse\x12;\n" +
	"\x10created_document\x18\x01 \x01(\v2\x10.worker.DocumentR\x0fcreatedDocument\x12&\n" +
	"\x06status\x18\x02 \x01(\v2\x0e.worker.StatusR\x06status\"\x80\x01\n" +
	"\x12GetDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x10include_metadata\x18\x03 \x01(\bR\x0fincludeMetadata\"k\n" +
	"\x13GetDocumentResponse\x12,\n" +
	"\bdocument\x18\x01 \x01(\v2\x10.worker.DocumentR\bdocument\x12&\n" +
	"\x06status\x18\x02 \x01(\v2\x0e.worker.StatusR\x06status\"6\n" +
	"\x14ListDocumentsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"o\n" +
	"\x15ListDocumentsResponse\x12.\n" +
	"\tdocuments\x18\x01 \x03(\v2\x10.worker.DocumentR\tdocuments\x12&\n" +
	"\x06status\x18\x03 \x01(\v2\x0e.worker.StatusR\x06status\"\xd7\x01\n" +
	"\x15UpdateDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12/\n" +
	"\x06update\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06update\x12$\n" +
	"\vif_revision\x18\x04 \x01(\x03H\x00R\n" +
	"ifRevision\x88\x01\x01\x12\x16\n" +
	"\x06upsert\x18\x05 \x01(\bR\x06upsertB\x0e\n" +
	"\f_if_revision\"}\n" +
	"\x16UpdateDocumentResponse\x12;\n" +
	"\x10updated_document\x18\x01 \x01(\v2\x10.worker.DocumentR\x0fupdatedDocument\x12&\n" +
	"\x06status\x18\x02 \x01(\v2\x0e.worker.StatusR\x06status\"\x8e\x01\n" +
	"\x15DeleteDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12$\n" +
	"\vif_revision\x18\x03 \x01(\x03H\x00R\n" +
	"ifRevision\x88\x01\x01B\x0e\n" +
	"\f_if_revision\"@\n" +
	"\x16DeleteDocumentResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\x0e.worker.StatusR\x06status*\xb8\x01\n" +
	"\n" +
	"StatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\f\n" +
	"\bCONFLICT\x10\x02\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x03\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x04\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x05\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x06\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\a\x12\x17\n" +
	"\x13FAILED_PRECONDITION\x10\b*C\n" +
	"\vReplicaRole\x12\f\n" +
	"\bFOLLOWER\x10\x00\x12\r\n" +
	"\tCANDIDATE\x10\x01\x12\n" +
	"\n" +
	"\x06LEADER\x10\x02\x12\v\n" +
	"\aLEARNER\x10\x032\x92\x03\n" +
	"\aStorage\x12O\n" +
	"\x0eCreateDocument\x12\x1d.worker.CreateDocumentRequest\x1a\x1e.worker.CreateDocumentResponse\x12F\n" +
	"\vGetDocument\x12\x1a.worker.GetDocumentRequest\x1a\x1b.worker.GetDocumentResponse\x12L\n" +
	"\rListDocuments\x12\x1c.worker.ListDocumentsRequest\x1a\x1d.worker.ListDocumentsResponse\x12O\n" +
	"\x0eUpdateDocument\x12\x1d.worker.UpdateDocumentRequest\x1a\x1e.worker.UpdateDocumentResponse\x12O\n" +
	"\x0eDeleteDocument\x12\x1d.worker.DeleteDocumentRequest\x1a\x1e.worker.DeleteDocumentResponseB4Z2github.com/10Narratives/distgo-db/pkg/proto/workerb\x06proto3"

var (
	file_proto_worker_worker_proto_rawDescOnce sync.Once
	file_proto_worker_worker_proto_rawDescData []byte
)

func file_proto_worker_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_worker_proto_rawDesc), len(file_proto_worker_worker_proto_rawDesc)))
	})
	return file_proto_worker_worker_proto_rawDescData
}

var file_proto_worker_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_worker_worker_proto_goTypes = []any{
	(StatusCode)(0),                // 0: worker.StatusCode
	(ReplicaRole)(0),               // 1: worker.ReplicaRole
	(*Status)(nil),                 // 2: worker.Status
	(*Document)(nil),               // 3: worker.Document
	(*ReplicaInfo)(nil),            // 4: worker.ReplicaInfo
	(*NodeStats)(nil),              // 5: worker.NodeStats
	(*ClusterHealth)(nil),          // 6: worker.ClusterHealth
	(*Empty)(nil),                  // 7: worker.Empty
	(*CreateDocumentRequest)(nil),  // 8: worker.CreateDocumentRequest
	(*CreateDocumentResponse)(nil), // 9: worker.CreateDocumentResponse
	(*GetDocumentRequest)(nil),     // 10: worker.GetDocumentRequest
	(*GetDocumentResponse)(nil),    // 11: worker.GetDocumentResponse
	(*ListDocumentsRequest)(nil),   // 12: worker.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),  // 13: worker.ListDocumentsResponse
	(*UpdateDocumentRequest)(nil),  // 14: worker.UpdateDocumentRequest
	(*UpdateDocumentResponse)(nil), // 15: worker.UpdateDocumentResponse
	(*DeleteDocumentRequest)(nil),  // 16: worker.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil), // 17: worker.DeleteDocumentResponse
	(*structpb.Struct)(nil),        // 18: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
}
var file_proto_worker_worker_proto_depIdxs = []int32{
	0,  // 0: worker.Status.code:type_name -> worker.StatusCode
	18, // 1: worker.Document.data:type_name -> google.protobuf.Struct
	19, // 2: worker.Document.created_at:type_name -> google.protobuf.Timestamp
	19, // 3: worker.Document.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: worker.ReplicaInfo.role:type_name -> worker.ReplicaRole
	5,  // 5: worker.ClusterHealth.node_stats:type_name -> worker.NodeStats
	19, // 6: worker.ClusterHealth.report_time:type_name -> google.protobuf.Timestamp
	18, // 7: worker.CreateDocumentRequest.document:type_name -> google.protobuf.Struct
	3,  // 8: worker.CreateDocumentResponse.created_document:type_name -> worker.Document
	2,  // 9: worker.CreateDocumentResponse.status:type_name -> worker.Status
	3,  // 10: worker.GetDocumentResponse.document:type_name -> worker.Document
	2,  // 11: worker.GetDocumentResponse.status:type_name -> worker.Status
	3,  // 12: worker.ListDocumentsResponse.documents:type_name -> worker.Document
	2,  // 13: worker.ListDocumentsResponse.status:type_name -> worker.Status
	18, // 14: worker.UpdateDocumentRequest.update:type_name -> google.protobuf.Struct
	3,  // 15: worker.UpdateDocumentResponse.updated_document:type_name -> worker.Document
	2,  // 16: worker.UpdateDocumentResponse.status:type_name -> worker.Status
	2,  // 17: worker.DeleteDocumentResponse.status:type_name -> worker.Status
	8,  // 18: worker.Storage.CreateDocument:input_type -> worker.CreateDocumentRequest
	10, // 19: worker.Storage.GetDocument:input_type -> worker.GetDocumentRequest
	12, // 20: worker.Storage.ListDocuments:input_type -> worker.ListDocumentsRequest
	14, // 21: worker.Storage.UpdateDocument:input_type -> worker.UpdateDocumentRequest
	16, // 22: worker.Storage.DeleteDocument:input_type -> worker.DeleteDocumentRequest
	9,  // 23: worker.Storage.CreateDocument:output_type -> worker.CreateDocumentResponse
	11, // 24: worker.Storage.GetDocument:output_type -> worker.GetDocumentResponse
	13, // 25: worker.Storage.ListDocuments:output_type -> worker.ListDocumentsResponse
	15, // 26: worker.Storage.UpdateDocument:output_type -> worker.UpdateDocumentResponse
	17, // 27: worker.Storage.DeleteDocument:output_type -> worker.DeleteDocumentResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_worker_worker_proto_init() }
func file_proto_worker_worker_proto_init() {
	if File_proto_worker_worker_proto != nil {
		return
	}
	file_proto_worker_worker_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_worker_worker_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_worker_proto_rawDesc), len(file_proto_worker_worker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_worker_proto_depIdxs,
		EnumInfos:         file_proto_worker_worker_proto_enumTypes,
		MessageInfos:      file_proto_worker_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_worker_proto = out.File
	file_proto_worker_worker_proto_goTypes = nil
	file_proto_worker_worker_proto_depIdxs = nil
}
